// <auto-generated />
using System;
using EntityOneToMore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityOneToMore.Migrations
{
    [DbContext(typeof(IskolaContext))]
    partial class IskolaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityOneToMore.Osztaly", b =>
                {
                    b.Property<int>("osztalyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("osztalyFonok")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("osztalyNev")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.HasKey("osztalyId");

                    b.ToTable("Osztaly");
                });

            modelBuilder.Entity("EntityOneToMore.Tanulo", b =>
                {
                    b.Property<int>("tanuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("osztalyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("szuletesiDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tanuloNev")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("tanuloId");

                    b.HasIndex("osztalyId");

                    b.ToTable("Tanulo");
                });

            modelBuilder.Entity("EntityOneToMore.Tanulo", b =>
                {
                    b.HasOne("EntityOneToMore.Osztaly", "Osztály")
                        .WithMany()
                        .HasForeignKey("osztalyId");
                });
#pragma warning restore 612, 618
        }
    }
}
